site_name: obstore
repo_name: developmentseed/obstore
repo_url: https://github.com/developmentseed/obstore
site_description: The simplest, highest-throughput Python interface to S3, GCS & Azure Storage, powered by Rust.
site_author: Development Seed
# Note: trailing slash recommended with mike:
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#publishing-a-new-version
site_url: https://developmentseed.org/obstore/
docs_dir: docs

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/developmentseed"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/developmentseed"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/development-seed"
  version:
    alias: true
    provider: mike

nav:
  - "index.md"
  - User Guide:
      - getting-started.md
      - cookbook.md
      - authentication.md
      - Integrations:
          - integrations/index.md
          - fsspec: integrations/fsspec.md
      - performance.md
      - Alternatives: alternatives.md
      - Troubleshooting:
          - AWS: troubleshooting/aws.md
  - Examples:
      - examples/fastapi.md
      - examples/minio.md
      - examples/pyarrow.md
      - examples/tqdm.md
  - Blog:
      - blog/index.md
  - API Reference:
      - obstore.store:
          - api/store/index.md
          - api/store/aws.md
          - api/store/gcs.md
          - api/store/azure.md
          - api/store/http.md
          - api/store/local.md
          - api/store/memory.md
          - api/store/config.md
          # - api/store/middleware.md
      - obstore.auth:
          - api/auth/azure.md
          - api/auth/boto3.md
          - api/auth/earthdata.md
          - api/auth/google.md
          - api/auth/planetary-computer.md
      - api/copy.md
      - api/delete.md
      - api/get.md
      - api/head.md
      - api/list.md
      - api/put.md
      - api/rename.md
      - api/sign.md
      - api/attributes.md
      - api/exceptions.md
      - api/file.md
      - obstore.fsspec: api/fsspec.md
  - Advanced Topics:
      - advanced/pickle.md
  - Developer Docs:
      - Contributing: dev/DEVELOP.md
      - Functional API: dev/functional-api.md
      - Overridden Defaults: dev/overridden-defaults.md
      - dev/pickle.md
  - CHANGELOG.md

watch:
  - obstore/python
  - docs

theme:
  language: en
  name: material
  custom_dir: docs/overrides
  logo: assets/logo_no_text.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: default
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: default
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.share

extra_css:
  - overrides/stylesheets/extra.css

plugins:
  - blog
  - search
  - social:
      enabled: !ENV [CI, false]
  - mike:
      alias_type: "copy"
      canonical_version: "latest"
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          paths: [obstore/python]
          options:
            # We set allow_inspection: false to ensure that all docstrings come
            # from the pyi files, not the Rust-facing doc comments.
            allow_inspection: false
            docstring_section_style: list
            docstring_style: google
            line_length: 80
            separate_signature: true
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_toc: true
            signature_crossrefs: true
            extensions:
              - griffe_inherited_docstrings

          import:
            - https://arrow.apache.org/docs/objects.inv
            - https://azuresdkdocs.z19.web.core.windows.net/python/azure-identity/latest/objects.inv
            - https://boto3.amazonaws.com/v1/documentation/api/latest/objects.inv
            - https://botocore.amazonaws.com/v1/documentation/api/latest/objects.inv
            - https://docs.aiohttp.org/en/stable/objects.inv
            - https://docs.pola.rs/api/python/stable/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://filesystem-spec.readthedocs.io/en/latest/objects.inv
            - https://google-auth.readthedocs.io/en/master/objects.inv
            - https://kylebarron.dev/arro3/latest/objects.inv
            - https://pystac.readthedocs.io/en/stable/objects.inv
            - https://requests.readthedocs.io/en/latest/objects.inv
  - redirects:
      redirect_maps:
        "fsspec.md": "integrations/fsspec.md"

# https://github.com/developmentseed/titiler/blob/50934c929cca2fa8d3c408d239015f8da429c6a8/docs/mkdocs.yml#L115-L140
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
